dependencies:
- name: lds-microservice
  version: 0.0.1
  repository: https://artifactory-tools.lsteck-demo-6ccd7f378ae819553d37d5f2ee142bd6-0000.us-east.containers.appdomain.cloud/artifactory/generic-local/lds-dev
