apiVersion: keymanagement.ibm/v1
kind: SecretTemplate
metadata:
  name: lds-microservice-example
  annotations:
    key-manager: key-protect
    key-protect/instanceId: 45acfec8-64be-4d1c-90f2-2c19b9be17b6
    key-protect/region: us-south
spec:
  labels: {}
  annotations: {}
  values:
    - name: url
      value: https://ibm.com
    - name: username
      b64value: dGVhbS1jYXA=
    - name: password
      keyId: c5d280cb-55c3-4909-b57a-01ad3ec8cb9c
